'use strict';

/**
 * CookieHelper.js — Comprehensive Cookie Import/Export Engine
 *
 * Supports:
 *   1. JSON format (EditThisCookie, Cookie-Editor, Puppeteer)
 *   2. Netscape HTTP Cookie File format (curl, wget, standard cookies.txt)
 */

class CookieHelper {
  /**
   * Parse any cookie format (JSON or Netscape) into normalized cookie array.
   * @param {string} raw
   * @returns {Array<Object>} Normalized cookies
   */
  static parse(raw) {
    if (!raw || typeof raw !== 'string' || !raw.trim()) {
      return [];
    }

    const text = raw.trim();

    // 1. Try parsing as JSON
    if (text.startsWith('[') || text.startsWith('{')) {
      try {
        const parsed = JSON.parse(text);
        const list = Array.isArray(parsed) ? parsed : [parsed];
        return list.map(c => this.normalizeCookie(c)).filter(Boolean);
      } catch (err) {
        // Fallback to line-by-line if JSON fails
      }
    }

    // 2. Parse Netscape format (tab-delimited or space-delimited)
    const lines = text.split(/\r?\n/);
    const cookies = [];

    for (let line of lines) {
      line = line.trim();
      if (!line || line.startsWith('#') || line.startsWith('//')) {
        continue; // Skip comments and empty lines
      }

      // Netscape standard: domain flag path secure expiration name value
      const parts = line.split('\t');
      if (parts.length >= 7) {
        const domain = parts[0].trim();
        const includeSubdomains = parts[1].trim().toUpperCase() === 'TRUE';
        const path = parts[2].trim() || '/';
        const secure = parts[3].trim().toUpperCase() === 'TRUE';
        const expires = parseInt(parts[4].trim(), 10) || -1;
        const name = parts[5].trim();
        const value = parts.slice(6).join('\t').trim();

        if (name) {
          cookies.push({
            name,
            value,
            domain: domain.startsWith('.') ? domain : (includeSubdomains ? `.${domain}` : domain),
            path,
            secure,
            httpOnly: false,
            expires: expires > 0 ? expires : undefined,
            sameSite: 'Lax',
          });
        }
      }
    }

    return cookies;
  }

  /**
   * Normalize a single cookie object from EditThisCookie / Puppeteer / JSON
   */
  static normalizeCookie(c) {
    if (!c || typeof c !== 'object' || !c.name) return null;

    let expires = undefined;
    if (c.expirationDate) expires = Math.floor(c.expirationDate);
    else if (c.expires) expires = Math.floor(c.expires);

    return {
      name: String(c.name).trim(),
      value: c.value !== undefined ? String(c.value) : '',
      domain: c.domain ? String(c.domain).trim() : '',
      path: c.path ? String(c.path).trim() : '/',
      secure: Boolean(c.secure),
      httpOnly: Boolean(c.httpOnly),
      expires: expires && expires > 0 ? expires : undefined,
      sameSite: c.sameSite || 'Lax',
    };
  }

  /**
   * Convert normalized cookies array to Netscape format string.
   * @param {Array<Object>} cookies
   * @returns {string} Netscape cookies.txt string
   */
  static toNetscape(cookies) {
    if (!Array.isArray(cookies) || cookies.length === 0) return '';

    let out = '# Netscape HTTP Cookie File\n# Generated by FWYS Antidetect Browser\n\n';
    for (const c of cookies) {
      if (!c.name || !c.domain) continue;
      const domain = c.domain;
      const sub = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = c.path || '/';
      const secure = c.secure ? 'TRUE' : 'FALSE';
      const exp = c.expires ? Math.floor(c.expires) : 0;
      const name = c.name;
      const value = c.value || '';

      out += `${domain}\t${sub}\t${path}\t${secure}\t${exp}\t${name}\t${value}\n`;
    }
    return out;
  }

  /**
   * Convert normalized cookies array to formatted JSON string.
   * @param {Array<Object>} cookies
   * @returns {string} Formatted JSON
   */
  static toJson(cookies) {
    if (!Array.isArray(cookies)) return '[]';
    return JSON.stringify(cookies, null, 2);
  }

  /**
   * Self test
   */
  static selfTest() {
    const netscapeSample = `.example.com\tTRUE\t/\tTRUE\t1750000000\tsession\tabc123\n`;
    const parsedNetscape = this.parse(netscapeSample);
    if (parsedNetscape.length !== 1 || parsedNetscape[0].name !== 'session') {
      throw new Error('Failed to parse Netscape cookie');
    }

    const jsonSample = JSON.stringify([{ name: 'test', value: '1', domain: 'test.com' }]);
    const parsedJson = this.parse(jsonSample);
    if (parsedJson.length !== 1 || parsedJson[0].name !== 'test') {
      throw new Error('Failed to parse JSON cookie');
    }

    const backToNetscape = this.toNetscape(parsedNetscape);
    if (!backToNetscape.includes('session\tabc123')) {
      throw new Error('Failed to convert back to Netscape format');
    }
  }
}

module.exports = CookieHelper;
